// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgS-VIm7NxH_80jU8ODWn6nINzoiPivw',
    appId: '1:25035354497:web:cec5869c5721aca552b880',
    messagingSenderId: '25035354497',
    projectId: 'schoolezy-production',
    authDomain: 'schoolezy-production.firebaseapp.com',
    storageBucket: 'schoolezy-production.appspot.com',
    measurementId: 'G-922MD8KCW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoLMN0M6ysXIFhkdRPY7A9bd2dGQOfy_s',
    appId: '1:25035354497:android:c6146a07a9236a7e52b880',
    messagingSenderId: '25035354497',
    projectId: 'schoolezy-production',
    storageBucket: 'schoolezy-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyRoRYlrvYckHFwapen8KL7GvdQxeBch8',
    appId: '1:25035354497:ios:9f31073fc35ecf2d52b880',
    messagingSenderId: '25035354497',
    projectId: 'schoolezy-production',
    storageBucket: 'schoolezy-production.appspot.com',
    androidClientId: '25035354497-oo7sm0ta6m58mra1n32sa31lak1kjoam.apps.googleusercontent.com',
    iosBundleId: 'in.schoolezy.schoolezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyRoRYlrvYckHFwapen8KL7GvdQxeBch8',
    appId: '1:25035354497:ios:6f0765ae9a3c44d552b880',
    messagingSenderId: '25035354497',
    projectId: 'schoolezy-production',
    storageBucket: 'schoolezy-production.appspot.com',
    androidClientId: '25035354497-oo7sm0ta6m58mra1n32sa31lak1kjoam.apps.googleusercontent.com',
    iosBundleId: 'in.schoolezy.schoolezy.RunnerTests',
  );
}
