// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Px-HlkpidnVY6eRz-3vwYF5dd9GjFX4',
    appId: '1:694513394103:web:ae695c693d00f73d330832',
    messagingSenderId: '694513394103',
    projectId: 'schoolezy-development',
    authDomain: 'schoolezy-development.firebaseapp.com',
    storageBucket: 'schoolezy-development.appspot.com',
    measurementId: 'G-PMJ16G87WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtxVs1osd9MJNw2awe0ubPvcBFdbbJMZQ',
    appId: '1:694513394103:android:94ec99c742b7e36a330832',
    messagingSenderId: '694513394103',
    projectId: 'schoolezy-development',
    storageBucket: 'schoolezy-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-tQl2mjAGfOsWl08GW626wUEcuUvGmo',
    appId: '1:694513394103:ios:8c36b67733372fb4330832',
    messagingSenderId: '694513394103',
    projectId: 'schoolezy-development',
    storageBucket: 'schoolezy-development.appspot.com',
    androidClientId: '694513394103-pch04t26bj8qnd82rdnrq23mi18ukpb1.apps.googleusercontent.com',
    iosBundleId: 'in.schoolezy.schoolezy.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-tQl2mjAGfOsWl08GW626wUEcuUvGmo',
    appId: '1:694513394103:ios:25a85e9e9659f580330832',
    messagingSenderId: '694513394103',
    projectId: 'schoolezy-development',
    storageBucket: 'schoolezy-development.appspot.com',
    androidClientId: '694513394103-pch04t26bj8qnd82rdnrq23mi18ukpb1.apps.googleusercontent.com',
    iosBundleId: 'in.schoolezy.schoolezy.RunnerTests',
  );
}
